# Generated by Django 3.1.5 on 2021-01-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='hostname',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hostname',
            field=models.CharField(default='anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='teach_shifts',
            field=models.CharField(default='11', max_length=40),
        ),
    ]
