# Generated by Django 3.1.6 on 2021-03-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20210122_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='studenttask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
