# Generated by Django 3.1.5 on 2021-01-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('for_sem', models.IntegerField()),
                ('for_year', models.IntegerField()),
                ('for_shift', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TaskReportStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('student_total_marks', models.FloatField()),
                ('got_marks', models.FloatField()),
                ('attended_tasks', models.IntegerField()),
                ('total_marks_all_tasks', models.FloatField()),
                ('total_num_tasks', models.IntegerField()),
                ('all_percentage', models.FloatField()),
                ('got_percentage', models.FloatField()),
                ('task_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_report_student', to='admins.taskreport')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('current_shift', models.IntegerField()),
                ('current_semester', models.IntegerField()),
                ('current_year', models.IntegerField()),
                ('hostname', models.CharField(max_length=100)),
                ('all_tasks_count', models.IntegerField()),
                ('submitted_tasks_count', models.IntegerField()),
                ('total_marks', models.FloatField()),
                ('got_marks', models.FloatField()),
                ('total_avg', models.FloatField()),
                ('got_avg', models.FloatField()),
                ('last_login', models.DateTimeField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attend', to='admins.tasksession')),
            ],
        ),
    ]
